<a href="https://colab.research.google.com/github/kjslei/AI-python/blob/main/25_05_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numphy

  Preparing metadata (setup.py) ... done
  Created wheel for numphy: filename=numphy-0.0.2-py3-none-any.whl size=9927 sha256=da1dbf6950737a4a4ae15eca6ac34c7b618500089a81ae720a2cee26dfc59d04
  Stored in directory: /root/.cache/pip/wheels/2a/8e/c6/f77cb69c2a3491c88d62551bc077449a64c65d183721bf19f9
Successfully built numphy


In [5]:
import numphy as np
print(np.__version__)

0.0.2


In [7]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [9]:
print(np.zeros((2, 3)))      # 2x3 크기의 0 배열
print(np.ones(5))            # 길이 5의 1 배열
print(np.arange(0, 10, 2))   # 0부터 10까지 2씩 증가
print(np.linspace(0, 1, 5))  # 0~1 사이를 5개로 나눈 배열
print(np.random.rand(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.81047424 0.40099074 0.73970005]


In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [16]:
print(np.zeros(5))
print(np.arange(2,12,2))
a=np.array([2,4,6])
b=np.array([10,20,30])
c=a*b
print(c)
filtered = c[c > 20]
print(filtered)

[0. 0. 0. 0. 0.]
[ 2  4  6  8 10]
[ 20  80 180]
[ 80 180]


In [17]:
pip install pandas

In [18]:
import pandas as pd
print(pd.__version__)

2.2.2


In [19]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [21]:
df.to_csv('students.csv',index=False)

In [22]:
df = pd.read_csv('students.csv')
print(df.head())

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [25]:
df = pd.read_csv('tested.csv')
print(df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   14.181209    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   21.000000    0.000000   
50%    1100.500000    0.000000    3.000000   27.000000    0.000000   
75%    1204.750000    1.000000    3.000000   39.000000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  417.000000  
mean     0.392344   35.627188  
std      0.981429   55.907576  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200  


In [27]:
df['Age']

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ... 
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64

In [28]:
df.dropna()

PassengerId  Survived  Pclass  \
12           904         1       1   
14           906         1       1   
24           916         1       1   
26           918         1       1   
28           920         0       1   
..           ...       ...     ...   
404         1296         0       1   
405         1297         0       2   
407         1299         0       1   
411         1303         1       1   
414         1306         1       1   

                                                  Name     Sex   Age  SibSp  \
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1   
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  48.0      1   
26                        Ostby, Miss. Helene Ragnhild  female  22.0      0   
28                             Brady, Mr. John Bertram    male  41.0      0   
..                                                 ...     ...   ...    ...   
404                       Frauenthal, Mr. Isaac Gerald    male  43.0      1   
405       Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0   
407                         Widener, Mr. George Dunton    male  50.0      1   
411    Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
414                       Oliva y Ocana, Dona. Fermina  female  39.0      0   

     Parch         Ticket      Fare            Cabin Embarked  
12       0          21228   82.2667              B45        S  
14       0    W.E.P. 5734   61.1750              E31        S  
24       3       PC 17608  262.3750  B57 B59 B63 B66        C  
26       1         113509   61.9792              B36        C  
28       0         113054   30.5000              A21        S  
..     ...            ...       ...              ...      ...  
404      0          17765   27.7208              D40        C  
405      0  SC/PARIS 2166   13.8625              D38        C  
407      1         113503  211.5000              C80        C  
411      0          19928   90.0000              C78        Q  
414      0       PC 17758  108.9000             C105        C  

[87 rows x 12 columns]